sudo: required

env:
  global:
    - PROJECT_NAME=tekwrks
    - DOCKER_IMAGE_NAME=user

language: node_js
node_js:
  - '10'

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

install:
  - npm install -g codecov

services:
  - docker

before_script:
  - yarn
  - yarn lint
  - yarn test --coverage && codecov

script:
  - make build

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - git clone https://github.com/tekwrks/MANAGE

deploy:
  - provider: script
    script: chmod 500 ./MANAGE/gcloud/push.sh && ./MANAGE/gcloud/push.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: WMq0fO4wmEBjVgbVFEnEqaoAtx2fIt4bWEZw4aoWsA13M7Vd87D0Jw77jm3Ziw0dy/Sp5qsDSKP7m6yAjqB9kv2gL9h0lTLFYrbw4UIgSmqOKrQU14TmlQaVmnWRMqzcbEI31Q3FNDbJfcZlQt8s8U5rZBLWw+Cay65rICJNjVJNRbtSPfdUK3DCOhO/MB5cnn30YxMceZevUV3mRb5YI+7n5E85/GKrp/JeQqNd37+aWN6FWU7jpTwew1NnbLlxKwB1FfI0mwiXH/vAyI562V8mOLtikWvGMAj3E9ST8qfq3y2NOcBCd3m4ziduciqMSCFCZssLvXq5EXncZ69iDJZ7Vds6I+NJ7OlALc+jITMpLMqjv6PjotbU2nQk8bWQsLhQGaO4ZS7t/tnzkwl7KNVegZTFJgDRod8H6zBUjh+TKl38UBtUG2bHvYibiFAtMOME5yjeEMGQdj8bpvKbbzame8OEO/J1RGBeuQx8SMiSMIg9Tj11TghSnUybFzzPAdrUcK6F9vmP5FjS1Oc2IezGjY6MCto2rx+cDFOHSBvYWgfuWlg9ouVIbDRGGKjnp6mh1X3sqTiUmvTcDGTAVylta2mGlbD0acKzlzKngO2+jGO8sAy3d9ZLpzIOZPvvJgbAbN6KhE2x/kraWrVIC/+qMDEIJFvQ3qL5LLNFlXY=
